{% set version = "5.12.1" %}

package:
  name: texlab
  version: {{ version }}

source:
  url: https://github.com/latex-lsp/texlab/archive/v{{ version }}.tar.gz
  sha256: 008db560759f207c31001dab94beb2229f0d263f86f4703f07d8eb8fc93e12c9

build:
  number: 0
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host: []
  run: []

test:
  commands:
    - texlab --version

about:
  home: https://texlab.netlify.app
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An implementation of the Language Server Protocol for LaTeX
  description: |
    A cross-platform implementation of the [Language Server Protocol](https://microsoft.github.io/language-server-protocol)
    providing rich cross-editing support for the [LaTeX](https://www.latex-project.org/) typesetting system.
    We provide an [extension](https://github.com/latex-lsp/texlab-vscode) for [Visual Studio Code](https://code.visualstudio.com).
  doc_url: https://texlab.netlify.app/docs
  dev_url: https://github.com/latex-lsp/texlab

extra:
  recipe-maintainers:
    - bollwyvl
