{% set version = "4.1.0" %}

package:
  name: texlab
  version: {{ version }}

source:
  url: https://github.com/latex-lsp/texlab/archive/v{{ version }}.tar.gz
  sha256: f7b5300c6fc93d7c339c755c67ea84f9c5daced2fb2735545d01a67ccf2ff770

build:
  number: 0
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []
  run: []

test:
  commands:
    - texlab --version

about:
  home: https://texlab.netlify.app
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An implementation of the Language Server Protocol for LaTeX
  description: |
    A cross-platform implementation of the [Language Server Protocol](https://microsoft.github.io/language-server-protocol)
    providing rich cross-editing support for the [LaTeX](https://www.latex-project.org/) typesetting system.
    We provide an [extension](https://github.com/latex-lsp/texlab-vscode) for [Visual Studio Code](https://code.visualstudio.com).
  doc_url: https://texlab.netlify.app/docs
  dev_url: https://github.com/latex-lsp/texlab

extra:
  recipe-maintainers:
    - bollwyvl
